# Generated by Django 4.2.1 on 2023-10-14 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="No data available", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(default="No data available", max_length=255),
                ),
                (
                    "last_name",
                    models.CharField(default="No data available", max_length=255),
                ),
                (
                    "date_of_birth",
                    models.CharField(default="No data available", max_length=255),
                ),
                (
                    "group_name",
                    models.CharField(default="No data available", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="No data available", max_length=255)),
                (
                    "start_date",
                    models.CharField(default="No data available", max_length=255),
                ),
                (
                    "end_date",
                    models.CharField(default="No data available", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ballot"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.candidate"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.election"
            ),
        ),
        migrations.AddField(
            model_name="ballot",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.election"
            ),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="No data", max_length=255)),
                ("last_name", models.CharField(default="No data", max_length=255)),
                ("date_of_birth", models.CharField(default="No data", max_length=255)),
                ("account_type", models.CharField(default="voter", max_length=5)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
